migrations/1506763059112-example-get-mapping.js, package.json
https://github.com/DivanteLtd/vue-storefront/issues/137
Now migration and restore dump work correct.
=> [#137] Fix migration bug and add correct setup command

package.json
Fixed incorrect node-command for "migrate".  Added missing keyword "node"
=> Fixed incorrect command for "migrate" command.

.gitignore
No need to put this file to repo.
=> Add auto-generated file .migrate to .gitignore

src/models/order.schema.json
Fixed telephone number pattern in Order validation schema to allow empty string
=> Fixed telephone number pattern to allow empty string

README.md
=> fix data format links

src/models/order.schema.json
In regards to CR https://github.com/DivanteLtd/vue-storefront/pull/462
=> Added User ID to Order model

src/worker/order_to_magento2.js
https://github.com/DivanteLtd/vue-storefront/issues/545
=> Receiving VAT id and passing it to Magento in regards to issue 545

src/api/cart.js, src/platform/magento2/cart.js, src/platform/magento2/magento2-rest-client/lib/cart.js
https://github.com/DivanteLtd/vue-storefront/issues/691
=> Backend support for payment and shipping methods sync with Magento

.gitignore, README.md, docker-compose.yml
Added a simple Kibana service to the docker-compose.yml file, so that out-of-the-box there is a way to search and show indexed data (mainly for debugging).
Updated README accordingly.
=> Add Kibana to the Docker configuration

config/default.json, src/api/imageable/lib/request-handler.js
- added an error output for failures when dugging to understand why the errors occur.
- added error catching logs too, when not rethrown
- Added imageable debug flag to the default config
=> Enhanced debug for imagable lib

README.md
- added requirements to the README.md
- corrected some spelling in the README.md
- added some links to the software used
- added a link to explain PWA
- added the -d flag for docker-compose to run in the background
- added a link to the LICENSE file
=> [#35] Documentation Update

config/default.json, src/index.js
More info:
https://github.com/DivanteLtd/vue-storefront/pull/1067
https://github.com/DivanteLtd/vue-storefront/issues/1026
=> Made host and port configurable in json configuration

config/default.json, src/api/img.js, src/index.js
=> Asset directory path made configurable

src/api/extensions/cms-data/README.md, src/api/extensions/cms-data/index.js
Magento 2 Cms  API extension for: https://github.com/DivanteLtd/vue-storefront/pull/1328
=> 1142 ad cms data api

src/worker/order_to_magento2.js
#33 
Sometimes an error occurs when sending an order. This is due to the fact that the shipping address first comes to the magento, and then the billing address. This pull request sets a clear priority - first the billing address, then the shipping address.
=> Refactor send order (order addresses)

src/worker/order_to_magento2.js
Pass payment method additional data <https://github.com/DivanteLtd/vue-storefront/blob/master/core/pages/Checkout.js#L168> on to magento
=> Add additional_data field to order payment sync

docker/vue-storefront-api/Dockerfile
imageable need imagemagick *and curl*. Added curl to the Dockerfile so that images can be downloaded from remote.
=> added missing curl dependency

README.md
\+ @pkarw Fixed readme for variants A/B of setup.
=> Fixed migrate command for variants A/B

package.json, scripts/kue.js, scripts/seo.js, yarn.lock
=> chore: fix seo.js and kue.js

src/graphql/elasticsearch/cms/resolver.js, src/graphql/elasticsearch/cms/schema.graphqls
https://github.com/DivanteLtd/vue-storefront/pull/2001
=> added graphql shecma/resolver for cms entities

README.md, scripts/mage2vs.js
Add delta indexer to mage2vs, also fixed a minor naming error of error variable.
=> Add delta indexer

src/graphql/elasticsearch/client.js
Apologies for the multiple PR's, it was easiest to do this from the GitHub GUI.
=> Let elasticsearch.js handle protocol accordingly

src/platform/magento2/tax.js
Apologies for the multiple PR's, it was easiest to do this from the GitHub GUI.
=>  Let elasticsearch.js handle protocol accordingly

src/api/product.js
Fixes issue where only root store prices are returned by the Product API render-list request. Now passes correct storeId
=> Fixes #162

scripts/seo.js
There are few things about `yarn seo redirects` that are not ideal:
- process hangs after execution - there is no return code
- fetching of categories is unnecessarily nested inside promise callback after fetching products
- the output of this task is printed into the console, but the debug mode is enabled by default + there are other console logs, so there is no easy way to use generated redirects
So I introduced async/await to run fetching one after another.
The output is now saved to the file and there is an option to pass a path to the output directory (by default is saves in the same directory as command execution, so running it via `yarn seo redirect` it will save it in project root). The filename is a name of the ES index + `redirects`, to be able to generate redirects for …
=> Better seo redirects generation

src/platform/magento1/order.js
Add magento1 route to create order
Related to PR: https://github.com/DivanteLtd/magento1-vsbridge-client/pull/2
=> Add magento 1 create order route

babel.config.js, docker-compose.nodejs.yml, package.json, src/api/order.js, src/index.js, src/models/order.schema.json, test.js, yarn.lock
=> update babel from 6.x to 7, add unicode characters support in order request validation

.travis.yml, migrations/1530101328854-local_es_config_fix.js, package.json, src/platform/magento1/tax.js, src/platform/magento1/util.js, src/platform/magento2/tax.js, src/platform/magento2/util.js
=> Building in Travis CI, code cleanup

scripts/mage2vs.js
Use Redis database from configuration.
=> Add database for redis

src/api/user.js
This fixes the linting issue in file src/api/user.js.
The issue was that decodedToken was initialize in the try catch which had let to `'decodedToken' is not defined         no-undef` error.
=> Fixed linting issue 

.gitignore, docker-compose.yml
=> #236 Mount ElasticSearch data to directory.

CHANGELOG.md, package.json
The schema files are not moved with `tsc` so we need to to move them our self.
=> Added moving of schema files to the dist folder

CHANGELOG.md, config/default.json
This is needed as we use the get method from the config package which throws when an config value is undefined.
=> Added assetPath to magento1 default config

src/models/userProfile.schema.json
=> 3 characters postcode in user profile address

src/graphql/elasticsearch/queryBuilder.js
- Corrected typo mistake, the variable name should be `optionsPrefix` instead of `optionsPrfeix`
=> Fixed typo mistake

src/api/user.js
Fix for userRegister.schema.extension.json and userProfile.schema.extension.json files, that are in .gitignore of src/modules/.gitignore, and are required. This fix makes the files not required, but loaded when they exist.
=> Fix for extended user files missing

CHANGELOG.md, src/platform/magento1/stock.js
* Since the msi support this param is an object and not a string anymore #260
=> Magento 1 stock check always return an empty object

CHANGELOG.md, src/platform/magento1/util.js
There is a bug in URL parsing for multistores in the API, see issue #275.
=> Magento 1.9 multistore support for API

CHANGELOG.md, docker-compose.nodejs.yml
Related to the issues #278 and #272
=> Add ./nodemon.json as docker mount

src/models/userRegister.schema.json
Add "addresses" property in userRegister schema, according to the new Vue Storefront feature: https://github.com/DivanteLtd/vue-storefront/pull/3055
=> Add "addresses" property to userRegister schema

README.md, config/default.json
I removed unused elements from `default.json` for the sake of readability.
=> Removing unused part of  #300

CHANGELOG.md, migrations/.common.js, src/api/catalog.js, src/api/extensions/gls-parcelshop-dk/cli.js, src/api/extensions/gls-parcelshop-dk/index.js, src/graphql/elasticsearch/client.js, src/platform/magento1/tax.js, src/platform/magento2/tax.js
In favour of issue #303 I added it to all connections I have found so far.
=> Force ES connections to use protocol config option

src/api/catalog.js
- Removed unused commented conditions in `src/api/catalog.js`
=> Removed unused commented code

CHANGELOG.md, src/api/cart.js, src/api/order.js, src/api/product.js, src/api/review.js, src/api/stock.js, src/api/sync.js, src/api/user.js, src/lib/util.js, yarn.lock
Backport functionality from #302
=> Bugfix/port functionality from #302

docker/vue-storefront-api/Dockerfile
apply analog change from https://github.com/DivanteLtd/vue-storefront/pull/3006
=> copy yarn.lock together with package.json

.github/workflows/nodejs.yml
Added github action ci so that we can test if we want that in the feature or if we want to stay on travis.
=> Added basic github action ci

src/lib/taxcalc.js
- invoke updateProductPrices with correct values
=> taxcalc.js - fix issue with deprecatedPriceFieldsSupport config.

src/lib/taxcalc.js
Restore some changes after https://github.com/DivanteLtd/vue-storefront-api/pull/375/files
=> WIP: Fixes for calculating lowest price after refactoring. #375.

config/default.json, src/lib/taxcalc.js
- add tax to special_price
- pass finalPriceInclTax for calculation
=> add tax to special_price

src/platform/magento2/o2m.js
See https://github.com/DivanteLtd/vue-storefront-api/issues/421
=> Improper usage of 'Error' constructor in './magento2/o2m.js'

src/lib/util.js
https://github.com/DivanteLtd/vue-storefront-api/issues/423
=> Explicit data extraction from 'Error' objects

CHANGELOG.md, ecosystem.json
Closes: #450 
After build app files are in dist/src
=> change path in ecosystem for o2m

CHANGELOG.md, config/default.json, src/lib/elastic.js
=> Add `request_cache` to ES url for version 6+

package.json, yarn.lock
=> bump version vsf-utilities

CHANGELOG.md, package.json, src/api/catalog.ts
apiError instead of throws to prevent infinite load on broken /api/catalog links
=> apiError instead of throws

package.json
I have updated some URL links from `DivanteLtd` to `vuestorefront`
=> Update links of some dependencies

.github/workflows/deploy.yml
GH Actions trigger on `test` and `demo` branches.
=> CLOUD_121/122 setup CI/CD

.github/workflows/deploy.yml
Conditionally run action, not step.
=> Fix conditionals in workflow
