- migrations/1507147503759-change-size-color.js
Custom magento2-sample-data attribute "pattern" had invalid mapping type (integer). Some values of this attribute were like "123,212" and now it's able to migrate records from `var/catalog.json`.
> Changes pattern attribute type from integer to string

- src/api/catalog.js
If `_resBody` parameter is `undefined`, we have an error while running `npm run dev`
> Fix for _resBody being undefined

- src/lib/taxcalc.js
- src/platform/magento2/tax.js
- src/processor/product.js
Hi!
It seems like the defaultCountry set in the config, for tax calculation is ignored. And instead the argument is hardcoded in the function arguments?
I wasn't sure where to resolve the issue, but the product processor seemed like the right place.
> Load default country for tax calculation from config

- docker-compose.yml
- elasticsearch/Dockerfile
- elasticsearch/config/elasticsearch.yml
- kibana/Dockerfile
- kibana/config/kibana.yml
* Elastic 5.6 (no breaking change)
* Official Elastic Docker image
* Better Elastic configuration handling
* Development mode (single node)
> Official Elastic Docker image

- src/api/extensions/cms-data/index.js
https://github.com/DivanteLtd/vue-storefront/issues/1426
SnowdogApps/magento2-cms-api version 1.1.0 should be installed in Magento 2 instance
https://github.com/SnowdogApps/magento2-cms-api/tree/1.1.0
> 1426 - cms integration by identifier

- README.md
\+ @pkarw  
The current doc url return:
> Corrected url for check API access.

- README.md
I found a few typos in the documentations. Corrected the container name to `vue-storefront-api_app_1` instead of `vuestorefrontapi_app_1`
Thanks for all the work you've done so far.
> Fixed incorrect commands

- docker-compose.yml
Resolves [#111](https://github.com/DivanteLtd/vue-storefront-api/issues/111)
Versions in `docker-compose.yml` and `docker-compose.nodejs.yml` now are the same.
> Changing version in docker-compose.yml

- config/elastic.schema.product.json
Missing mapping data type for field "news_to_date". In my elasticsearch index, "news_to_date" have type "string" and can't be filtered by date correctly.
> custom field type for news_to_date

- scripts/db.js
Call `process.exit()` when successfully creating a new db.
> bugfix/128 - Exit process on success

- src/graphql/resolvers.js
- src/graphql/schema.js
With this update custom entities could be added through extensions by simply creating  : 
- one or more `*.graphqls` files with the extension schema(s)
- a `resolver.js` file with the extension entity resolvers
**For example :** 
file `src/api/extensions/demo-graphql-extension/schema.graphqls`
```
type Query {
hello(name: String): String
}
```
file `src/api/extensions/demo-graphql-extension/resolver.js`
```
const resolver = {
Query: {
hello: (parent, args) => {
const { name } = args
return `hello ${name}`
}
}
};
export default resolver;
```
Resolvers and schemas will be merge with the core ones.
> Allow custom schemas and resolvers addition from extensions level

- config/default.json
- src/api/extensions/mail-service/index.js
https://github.com/DivanteLtd/vue-storefront/issues/1812
In default.json under extensions.mailService.transport the default SMTP transport is defined.
Also in mail-service extension there's a check if SMTP transport is defined in configuration file. If not, 500 will be returned with explanation text.
> default SMTP transport, check if transport is set

- package.json
- yarn.lock
This is WIP till [#46](https://github.com/DivanteLtd/mage2vuestorefront/pull/46) is not merged.
This updates elasticsearch.js same way that in `mage2vuestorefront` PR, but in this project elastic apiVersion  is set to 5.5 so there was nothing else to be done.
Migrate had only small changes:
* error syntax change
* fix on promise callback
* slug update
* some docs changes
so it looks like nothing which could make some trouble
[changes commits](https://github.com/tj/node-migrate/commits/master)
Soap had enhancements, but doesn't look like breaking changes. Tried to find potential problems with that but haven't found any.
[full changelog](https://github.com/vpulim/node-soap/blob/master/History.md)
> Bugfix dependencies audit problem

- src/api/index.js
This should allow extensions to be included as their own separate module.
Registering works exactly the same so this should be fully backwards compatible, eg:
1. Run `yarn add my-npm-extension`
2. Add `my-npm-extension` to `local.json`'s `registeredExtensions`
3. Restart server
API should be available at: `/api/ext/my-npm-extension/:methodName`
The register method will still check the local `extensions` folder first so they can be overwritten if needed.
> Allow extensions to be installed as npm modules

- src/lib/taxcalc.js
Currently, special prices don't work well when dates are set as a range, b/c there is logical or in the condition, so effectively almost any "from" date fits the condition and don't set the special price to 0, which leads to inconsistencies on the front-end.
> Special price dates checking fix

- config/default.json
- scripts/mage2vs.js
Related to [mage2vuestorefront#61](https://github.com/DivanteLtd/mage2vuestorefront/issues/61) this adds the config/env variable for excluding disabled products from Magento import. Adds to `config/default.json` and `mage2vs.js`.
> Adds config variable for excluding disabled products

- README.md
There was an issue in the README causing the wrong text to be formatted as code near the end of the file.
> Fixed code formatting in README

- src/lib/image.js
This PR removes the following warning messages which are displayed when resizing an image from the api:
> DeprecationWarning: max() is deprecated, use resize({ fit: "inside" }) instead
> DeprecationWarning: withoutEnlargement() is deprecated, use resize({ withoutEnlargement: true }) instead
> Do not use deprecated functions

- src/platform/magento1/tax.js
The value 5.5 was hardcoded into the source code but the value from
this._config.elasticsearch.apiVersion should be used when creating the
elasticsearch client.
> Changed apiVersion from hardcoded value to config value

- src/graphql/elasticsearch/catalog/processor.js
- src/graphql/elasticsearch/catalog/resolver.js
- src/processor/product.js
The GraphQL endpoint is not setting the required `req` and `res` parameters in the processor adapter so queries to the `products` query are throwing the following error:
```
Entering ProductProcessor::process
Taxes will be calculated for GB  false
Elasticsearch INFO: 2019-04-17T18:25:22Z
Adding connection to http://localhost:9200/
Elasticsearch DEBUG: 2019-04-17T18:25:22Z
starting request {
"method": "POST",
"path": "/vue_storefront_magento_1/taxrule/_search",
"body": {},
"query": {}
}
Elasticsearch DEBUG: 2019-04-17T18:25:22Z
Request complete
TypeError: Cannot read property 'query' of undefined
at ProductProcessor.<anonymous> (/Users/jahvi/Repositories/vue-storefront-api/src/processor/product.js:33:21)
> Add missing parameters to processor adapters

- scripts/mage2vs.js
- src/api/stock.js
> [2310-msi] Default stockId and from storeView.

- CHANGELOG.md
- ecosystem.json
- package.json
- tsconfig.json
- yarn.lock
Here the problem was that node does not use "import" the same way typescript or babel so i have changed the module resolution to commonjs which does fixes one of the problems.
The second one was that we still use babel-node for pm2 which is removed form the package.json as we now use typescripts compiler (tsc --build) to transpile the code. 
The last problem was the babel has copied the graphql files for us but *tsc* does not do it for us so we needed to a new build step which does it for us. 
This is now handel with [cpx](https://www.npmjs.com/package/cpx) [github](https://github.com/mysticatea/cpx).
> Fixed bug around instand crash on start and graphql files getting not moved anymore.

- CHANGELOG.md
- README.md
- scripts/mage2vs.js
Since in the mage2vuestorefront adapter an error is thrown if something goes wrong my idea was to catch it here and display a proper message
> #235(mage2vs) feat: add import of cms blocks and pages

- CHANGELOG.md
- src/models/order.schema.js
Fix `error: uncaughtException: Unexpected token export` when running o2m
> Fix o2m order schema parsing

- src/platform/magento2/o2m.js
As its common to show customers an OrderNumber which is in no relation to the ID used for the Order Entity, it makes sense to introduce this in a platform agnostic way.
Magento for example uses the increment_id for the order number. It will likely be named different for other systems.
To prevent BC breaks in the future, the name should be carefully thought out.
Currently the recent solution for the MyOrder Page is relying on the existence of increment_id, which may not exist for other Systems.
related issue:
https://github.com/DivanteLtd/vue-storefront/issues/2743
Follow Up changes:
- if this value gets added here, it next needs to be added to the ThankYouPage
- The MyOrder Page needs to be aligned in usage of this value.
- needs maybe change on API side?
- should implement a fallback for …
> introduce orderNumber to order creation endpoint

- CHANGELOG.md
- config/custom-environment-variables.json
- config/default.json
- scripts/kue.js
- scripts/mage2vs.js
- src/api/sync.js
- src/platform/magento2/o2m.js
Closes #267 
With this update all areas in this repo that connect with Redis now use the optional `redis.auth` value if it's available. To use it you simply need to set the env variable `REDIS_AUTH` to the appropriate password. If you don't set this variable it will default to `false` and will not be used.
> Use Redis Auth when provided

- config/default.json
- src/api/extensions/example-processor/index.js
- src/api/extensions/example-processor/processors/my-product-processor.js
Related to PR #269. An example extension to show how to configure a result processor
> Example extension for implementing a custom result processor (PR #269)

- .travis.yml
- CHANGELOG.md
I was looking at the current Travis config and I noticed that the build stage was there twice (one time fo each supported NodeJS version). Using the YAML anchor function we can remove that duplication. This will also lead to a smaller Travis config in the future, for example, if we want to support Node v12.
> Remove duplication fom Travis config

- src/processor/product.js
Two parameters added to Product results processor :
1. Request now passed to PlatformFactory, which was defaulting to null
2. Elasticsearch index name now passed to custom processors (PR #269). It can be used to determine the current store
> Fix missing parameter passed to result processors

- CHANGELOG.md
- scripts/mage2vs.js
Closes #281 
When running `mage2vs import` and `productsdelta` the currency code is now passed to the config if it's available in `storeView.i18n.currencyCode`.
> Include Magento Currency Code in mage2vs

- src/platform/magento1/util.js
This does fix 3 things 
* Looking in the magento2 config for store api url
* changing the URL when a config value for magento1 for the store was found
* Adding the store code to the end of the url which is not working in the magento1 module
> Fixed store specific API config/url in util.js

- CHANGELOG.md
- config/default.json
- src/api/extensions/mailchimp-subscribe/index.js
The default status was set to subscribed, but since GDPR needs an Opt-In pending would fit way better.
@lukeromanowicz i created a new PR, since i accidentally did a reformat of the code.
I've updated the changelog, please check if everything is alright.
> Feature add setting for mailchimp subscription status

- .gitignore
- CHANGELOG.md
- README.md
- package.json
- src/helpers/loadAdditionalCertificates.ts
- src/index.ts
- yarn.lock
> Autoload self signed certificates from config/certs directory

- CHANGELOG.md
- scripts/mage2vs.js
Closes #232 . Adds optional parameter `--generate-unique-url-keys` to the `mage2vs import` command. It defaults to `false`. This is passed along to the `mage2vuestorefront` scripts to tell it if it should generate unique url keys for categories or not.
> Disable unique url generation for categories import

- config/default.json
- package.json
- src/api/img.js
- src/image/action/abstract/index.ts
- src/image/action/factory.ts
- src/image/action/local/index.ts
- src/image/cache/abstract/index.ts
- src/image/cache/factory.ts
- src/image/cache/file/index.ts
- src/index.ts
- yarn.lock
With this we get a local action witch is the current behavior.
Then we have file caching which is disabled by default. This creates
and md5 of the URL and for that he saves the processed image to file.
With this you can change the logic of caching (s3, redis, ...) and you can change the implementation of processor which and what you can to with the image. 
This is a basic implementation and I would think needs better naming.
> Implemented basic image processing/caching factories

- package.json
- yarn.lock
As per [#312](https://github.com/DivanteLtd/vue-storefront-api/issues/312).
* Upgraded `package.json` graphql version
* Upgraded updated `yarn.lock` file
> #312 upgrade graphql version to v0.13+

- README.md
- config/default.json
- src/api/review.js
Fix review_status field vulnerability  https://github.com/DivanteLtd/magento2-review-api/issues/17
Set review status in configuration. 
Related PR to VSF:
https://github.com/DivanteLtd/vue-storefront/pull/3546
> Adding new reviews - get status from configuration.

- CHANGELOG.md
- src/api/extensions/mailchimp-subscribe/index.js
- src/lib/taxcalc.js
- src/platform/magento1/tax.js
- src/platform/magento2/tax.js
I've added error handling for Mailchimp as there is only `4**` code in the response which is hard to recognise as an error in the UI.
Also I've updated `taxtCalc` to be consisted with this one in VSF.
> Error response when there is problem with Mailchimp

- CHANGELOG.md
- config/elastic.schema.attribute.json
As of 5.0 value not_analyzed is no longer applicable.
Reference: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_literal_index_literal_property
Citation: On all field datatypes (except for the deprecated string field), the index property now only accepts true/false instead of not_analyzed/no. The string field still accepts analyzed/not_analyzed/no.
As per https://www.elastic.co/guide/en/elasticsearch/reference/1.4/mapping-core-types.html, not_analyzed means that its still searchable, but does not go through any analysis process or broken down into tokens.
As per https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html, index means Should the field be searchable? Accepts true (default) or false.
So, changing index value …
> Done: Remove index value not_analyzed for some fields as it is deprecated #334

- src/api/user.js
- src/platform/magento2/user.js
In support of [magento2-rest-client#3](https://github.com/DivanteLtd/magento2-rest-client/issues/3) and PR [magento2-rest-client#19](https://github.com/DivanteLtd/magento2-rest-client/pull/19).
Adds optional ability to paginate order history with the default values of 20 items and page 1.
> Order History Pagination

- CHANGELOG.md
- src/api/user.js
- src/lib/taxcalc.js
- src/platform/magento2/user.js
Refactor `taxcalc.js` similar to frontend PR https://github.com/DivanteLtd/vue-storefront/pull/3746
> refactor taxcalc similar to frontend

- src/lib/taxcalc.js
- if product doesn't have field 'special_price', we get "Nan" value (and we can have null value in product.price), similar  case if for 'final_price' (problem appears after refactoring)
- fix calculating minimal price for configurable products. If `product.final_price < price.price' - final_price was not used as price
>  Fixes for calculating lowest price after refactoring.

- src/api/user.js
This change closes https://github.com/DivanteLtd/vue-storefront/issues/3892 With `websiteId: undefined` we point to default store in magento (case without multistore).
> send /reset-password with undefined websiteId as default

- CHANGELOG.md
- src/lib/image.js
The `crop` function was deprecated in v0.21.0 and removed in v0.22.0 of the Sharp image processor
https://sharp.pixelplumbing.com/en/stable/changelog/
This PR replaces the `crop` call with the new `fit` parameter of the `resize` function
> Replace Sharp's crop function

- CHANGELOG.md
- config/default.json
- src/api/index.js
- src/api/url.js
- src/api/url/index.js
- src/api/url/map.js
- src/lib/elastic.js
Close: https://github.com/DivanteLtd/vue-storefront/issues/3942
Description:
This module search for record in multiple entities based on url value.
Config:
```
"includeFields": ["url_path", "identifier", "id", "slug", "sku", "type_id"],
// Here we can define base fields that we want to fetch if there is record in ES.
// Those fields are needed to build proper url object on frontend side.
// But you can also send in body fields that you want.
// Example: {"url": "about-us", "includeFields": ["content"]}
```
```
"searchedFields": ["url_path", "identifier"],
// Here we can define which field value equals to url value.
// By default we search "url_path" for product/category and "identifier" for cms_page
```
```
"searchedEntities": ["product", "category", "cms_page"]
// Here we have list of …
```
> add url module

- CHANGELOG.md
- src/lib/util.js
Check message property instead of errorMessage in apiError function to return correct error message from API.
> #378 Check message prop instead of errorMessage

- CHANGELOG.md
- src/platform/magento1/tax.js
Add fallback if `sourcePriceInclTax` and `finalPriceInclTax` are not set in multistore store object in `magento1` platform.
If you set this values only globally (not for each store) but use `multistore` mode, the values of both parameters will alway be `undefined` because  they are not set in the store object which is iterated through: https://github.com/DivanteLtd/vue-storefront-api/blob/30e1938a933146634b06590d3c84bf5f9b06ff05/src/platform/magento1/tax.js#L21-L31
I added a simple fallback so the check which happens later in this method can replace the empty values with the global one:
https://github.com/DivanteLtd/vue-storefront-api/blob/30e1938a933146634b06590d3c84bf5f9b06ff05/src/platform/magento1/tax.js#L42-L47
> Add fallback for `sourcePriceInclTax` and `finalPriceInclTax` in `magento1` platform

- CHANGELOG.md
- config/default.json
- src/lib/elastic.js
There are cases when you need a HTTP authentication for you ElasticSearch connection.
I'm using the official ES cloud for example and this uses an user authentication using a password and username.
This isn't supported yet in the `src/lib/elastic.js:getClient()` method of the current `develop` branch.
I added another config parameter to the method to make it possible to us a authentication. I also put the part for the `requestTimeout` into the config file to make this optionally configurable.
> Add  ES client support for authentication

- CHANGELOG.md
- src/api/url/map.ts
Solves #401
> The new `/api/url/map/vue_storefront_catalog_de` endpoint returns a product object to the VSF which isn't processed by the product processor. In the VSF the url action method `saveFallbackData` then saves this response to the `elasticCache` storage and the data is shown wrong in the VSF:
> https://github.com/DivanteLtd/vue-storefront/blob/develop/core/modules/url/store/actions.ts#L193-L194
> 
> In my case the product prices are missing when I load a product details page because it is first loaded via the URL mapper, then stored in the cache and just loaded from that for the rest of the page.
> 
> This is related to the latest `develop` branch of the API and the VSF.
> Process product data in new URL mapper endpoint (#401)

- CHANGELOG.md
- config/default.json
- docker-compose.nodejs.yml
- docker-compose.varnish.yml
- docker-compose.yml
- docker/varnish/Dockerfile
- docker/varnish/README.md
- docker/varnish/config.vcl
- docker/varnish/docker-compose copy/docker-compose.nodejs.yml
- docker/varnish/docker-compose copy/docker-compose.varnish.yml
- docker/varnish/docker-compose copy/docker-compose.yml
- docker/varnish/docker-compose/docker-compose.nodejs.yml
- docker/varnish/docker-compose/docker-compose.varnish.yml
- docker/varnish/docker-compose/docker-compose.yml
- src/api/catalog.ts
- src/api/invalidate.ts
Hello.
I've just prepared a Varnish configuration with autoinvalidating ES. It is able to really improve your page's speed. 
Request to the:
```
/api/catalog/vue_storefront_catalog_eu/product/_search
```
Without Varnish (132ms): 
With Varnish (79ms):
Elasticsearch is pretty good at caching. However, let's look at extensions that fetch some data from a real backend (M2). Example of my extension that fetches menu without Varnish (791ms):
As you see TTFB is really huge. It is because API sends the request to Magento. So normally it goes through VSF-API -> Magento. When we use Varnish we cache it in front of the VSF-API so the response is... a bit faster! (84ms)
I am also wondering about caching `Pull Cart request` and invalidate it with `Update & Delete`. I have to check this idea.
Inside my …
> Varnish Cache with auto invalidation for ES

- src/api/extensions/elastic-stock/index.js
This fixes the issues described in #402, #389 and #388
* makes `elastic-stock` extension compatible with both ES5 and ES7
* Allows for stock fetch of configurable children that is set as "Not Visible Individually"
> Bug fix for elastic-stock extension

- CHANGELOG.md
- README.md
- config/default.json
- src/api/catalog.js
- src/api/extensions/elastic-stock/index.js
- src/lib/elastic.js
- src/lib/util.js
- src/models/order.schema.js
- src/platform/magento1/tax.js
- src/platform/magento2/o2m.js
- Add save address on place order - @lucasqm (#394)
- Add ElasticSearch client support for HTTP authentication - @cewald (#397)
- Add error handling for catalog and add header 'X-VS-Cache-Tags' to response - @gibkigonzo
- Add fallback for `sourcePriceInclTax` and `finalPriceInclTax` in `magento1` platform - @cewald (#398)
- Add default ES index to config and update `getStockList` - @gibkigonzo (#405)
- Makes elastic-stock extension compatible with both ES5 and ES7. Allows for stock fetch of configurable children that is set as "Not Visible Individually" - @didkan (#410)
> backport fixes from develop to 1.11.1

- CHANGELOG.md
- src/platform/magento1/user.js
Add `resetPasswordUsingResetToken` method to `magento1` platform.
I also made related changes in the `magento1-vsbridge-client` here:
https://github.com/DivanteLtd/magento1-vsbridge-client/pull/11
> Add `resetPasswordUsingResetToken` to `magento1` platform

- CHANGELOG.md
- src/api/catalog.ts
- src/models/order.schema.js
We put output into cache before formatting, so when we get it from cache we need to add formater.
> add outputFormatter to response from cache

- .eslintignore
- CHANGELOG.md
- config/default.json
- package.json
- src/api/catalog.ts
- src/api/extensions/example-custom-filter/filter/catalog/SampleFilter.ts
- src/api/extensions/example-custom-filter/index.ts
- src/helpers/loadCustomFilters.ts
- src/models/order.schema.js
- yarn.lock
Update to `storefront-query-builder` version `1.0.0`
This is connected to the update of `storefront-query-builder` to support new features as extendable filters and more customizable sorting.
Read more about here: https://github.com/DivanteLtd/storefront-query-builder/pull/6
---
* Add helper to import custom filters automatically
* Add a sample custom filter in `example-custom-filter` module
* Update `bodybuilder` package to `2.2.21` to be able to use the `clone` method
* Add `.eslintignore` to ignore `node_modules`
The version number I added is not yet connected to a valid `npm` package and therefore would fail while `yarn install`. To test it, you can checkout the new `storefront-query-builder` branch of PR above and connect it to your local `yarn` instance using `yarn build && yarn …
> Update to `storefront-query-builder` version `1.0.0`

- CHANGELOG.md
- config/default.json
- src/index.ts
A simple call to  https:/demo.vuestorefront.io/api/catalog  lead to an exposure. The exception expose full path and some node modules names.
Calls that need to submit JSON (Content-type: application/json) can be exploited by sending anything but valid JSON :
curl -i -s -k -X $'GET' -H $'Host: demo.storefrontcloud.io' -H $'Accept: */*' -H $'Content-Type: application/json' -H $'Origin: https://demo.vuestorefront.io' -H $'Content-Length: 2' --data-binary $'\x0d\x0a' $'https://demo.storefrontcloud.io/api/cart/pull?token=&cartId='
before:
```
HTTP/1.1 400 Bad Request
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Link
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 1083
Date: …
```
> disable showing stack for invalid requests

- CHANGELOG.md
- src/api/catalog.ts
I removed the `_outputFormatter` from output-cache response in the `catalog` endpoint.
This change came with this commit: e45bbec373e405df02390d5bb62fdb80bae3a2d5.
I'm not sure if this is correct. If I see straight, the output is already formatted before it is put into the cache using the `resultProcessor`.
In my case, this leads into an exception on each cached request – the first (uncached) works, the second fails with:
```
TypeError: Cannot read property 'map' of undefined
at _outputFormatter (/vue-storefront-api/src/api/catalog.ts:34:50)
at /vue-storefront-api/src/api/catalog.ts:180:18
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
This, of course, only appears if `useOutputCache` is enabled.
> Improve `_outputFormatter` on cache catalog-response to prevent exception

- CHANGELOG.md
- src/api/order.ts
- src/api/user.ts
- src/platform/magento1/util.js
This fixes two things:
1. The schema extension files won't be found at the moment because the path needs to be relative `fs.existsSync()`. Right now the `fs.existsSync` check always returns `false`.
1. Also the resolution of the VSF bridge URL of the `magento1` platform has a flacky RegExp which will return true if a store-code string is found anywhere in the string but it should be match for strings that are surrounded by `/` only.
> Bugfix for wrong JSON scheme url's and hostname resolution for `magento1` platform

- CHANGELOG.md
- src/api/img.ts
Closes: #434 
Description:
If img middleware can't fetch image then it sent response in `prossesImage`. Same can happen in other methods of `ImageAction`. This change will check if headers has been already send
> check if headers has been already sent in image middleware

- CHANGELOG.md
- src/api/catalog.ts
- src/lib/util.js
Closes: #442
ES returns error object where status code is a string:
```
{ Error: connect ETIMEDOUT 51.255.29.86:443
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
errno: 'ETIMEDOUT',
code: 'ETIMEDOUT',
syscall: 'connect',
address: '51.255.29.86',
port: 443 }
```
So when we pass to `apiStatus` a string then it will fail as unhandled rejection:
```
(node:8036) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: ETIMEDOUT
at ServerResponse.writeHead (_http_server.js:209:11)
at ServerResponse.writeHead (/home/tkostuch/projects/vue-storefront-api/node_modules/on-headers/index.js:44:26)
at ServerResponse._implicitHeader (_http_server.js:200:8)
at write_ (_http_outgoing.js:585:9)
at ServerResponse.end (_http_outgoing.js:702:5)
at …
```
> add error status code as number in apiError

- CHANGELOG.md
- src/image/action/local/index.ts
This value is used as the default value for the `Cache-Control: max-age=XXXXXX` header - which is measured in seconds, not milliseconds - making the current default value equal to 365250 days instead of 365.25 as I assume was the intention.
To make it clearer what this value is supposed to be, I think it makes sense to use a calculation here instead of just a number.
> Fix default value for `maxAgeForResponse`

- config/default.json
- src/api/catalog.ts
- src/lib/elastic.js
Added 3 configuration values:
```{
"elasticsearch":
"useRequestFilter": false,
"overwriteRequestSourceParams": false,
"requestParamsBlacklist": [], 
}
}
```
`useRequestFilter` is responsible for enabling/disabling ES request filtering
`overwriteRequestSourceParams` decide if you want to overwrite or merge values
`requestParamsBlacklist` allow you to filter out selected attributes
> Allow filter elasticsearch request for security reasons

- CHANGELOG.md
- src/api/catalog.ts
apiError instead of throws to prevent infinite load on broken /api/catalog links
> apiError instead of throws on develop

- CHANGELOG.md
- src/api/attribute/service.ts
closes #579
* Adds cache tag attribute when caching so that attributes can be purged using cache tag
* Adds indexName to cache key so we store multistore attributes separately
> Bugfix: Attributes cache tag and multistore handling
